config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get "log_in", to: "devise/sessions#new"
  end

  get 'welcome', to: 'static#welcome'
  get 'about_me', to: 'static#about_me'
  get 'blog', to: 'posts#index'

  resources :posts do
    member do
      put 'toggle_published'
    end
    collection do
      get 'admin'
    end
  end

  resources :projects do
    member do
      put 'toggle_published'
    end
    collection do
      get 'admin'
    end
  end

  root 'posts#index'
  get '/*foo', to: redirect('/')

end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { order(created_at: :desc, id: :desc) }

  validates :title, :content, presence: true
  validates :title, length: { in: 2..255 }
  validates :author_id, presence: true
  validates :content, length: { in: 4..200_000 }

  belongs_to :author, class_name: 'User'

end

app/models/project.rb
class Project < ActiveRecord::Base
  default_scope { order(created_at: :desc, id: :desc) }

  mount_uploader :screenshot, ScreenshotUploader

  validates :title, :content, presence: true
  validates :title, length: { in: 2..255 }
  validates :content, length: { in: 4..200_000 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper

  before_filter :filter_admin, except: [:index, :show]

  def index
    @posts = posts
    @projects = projects
  end

  def show
    @post = Post.find(params[:id])
    redirect_to root_path unless @post.published || admin?
    @projects = projects
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = 'Post updated'
      redirect_to @post
    else
      render edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render action: 'new'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to :admin_posts
  end

  def admin
    @posts = Post.all
  end

  def toggle_published
    post = Post.find(params[:id])
    post.published = !post.published
    post.save!
    redirect_to :admin_posts
  end

  private

    def filter_admin
      redirect_to :root unless admin?
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ApplicationHelper

  before_filter :filter_admin, except: [:index, :show]

  def index
    @posts = posts
    @projects = projects
  end

  def show
    @posts = posts
    @project = Project.find(params[:id])
    redirect_to root_path unless @project.published || admin?
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = 'Project updated'
      redirect_to @project
    else
      render edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render action: 'new'
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to :admin_projects
  end

  def admin
    @projects = Project.all
  end

  def toggle_published
    project = Project.find(params[:id])
    project.published = !project.published
    project.save!
    redirect_to :admin_projects
  end

  private

    def filter_admin
      redirect_to :root unless admin?
    end

    def project_params
      params.require(:project).permit(:title, :content, :screenshot)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  include ApplicationHelper

  before_filter :indexes

  def welcome
  end

  def about_me
  end

  private
    def indexes
      @posts = posts
      @projects = projects
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

  def admin?
    return current_user && current_user.admin?
  end

  def posts
    admin? ? (return Post.all) : (return Post.where(published: true))
  end

  def projects
    admin? ? (return Project.all) : (return Project.where(published: true))
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_contact_links.html.haml
.contact_links
  %span.contact_link
    = image_tag 'email_icon.png', class: 'email_icon'
    %span.email_text
      = link_to 'nbarnes@gmail.com', 'mailto:nbarnes@gmail.com'
  %br
  %span.contact_link
    = image_tag 'tweeter_logo_white.png', class: 'twitter_icon'
    %span.twitter_text
      = link_to '@foxbarnes', 'https://twitter.com/FoxBarnes'
  %br
  %span.contact_link
    = image_tag 'InBug-60px-TM.png', class: 'linkedin_icon'
    %span.linkedin_text
      = link_to 'linkedin/nbarnes2', 'https://www.linkedin.com/in/nbarnes2'
  %br
  %span.contact_link
    = image_tag 'GitHub-Mark-120px-plus.png', class: 'github_icon'
    %span.github_text
      = link_to 'github/nbarnes', 'https://github.com/nbarnes/Portfolio'

app/views/layouts/_footer.html.haml
#footer_contact_links
  = render ('layouts/contact_links')

app/views/layouts/_header.html.haml
#header_pane

  #login_and_flash
    - if current_user
      You are logged in as
      = current_user.email
      = " - "
      = link_to('Log out', destroy_user_session_path, :method => :delete)
      = " - "
      = link_to('Posts Admin', admin_posts_path)
      = " - "
      = link_to('Projects Admin', admin_projects_path)


    #flash_display
      - flash.each do |key, value|
        %div{:class => '<%=flash_class(key) %>'}
        = value
  %br
  %br

  #header_contact_links
    = render ('layouts/contact_links')

  #portrait_and_name_pane.clearfix.title
    #header_portrait
      = link_to root_url do
        = image_tag 'nath1.jpg', id: 'header_portrait_image'

    #header_text
      = link_to 'A Lightsaber Mind', root_url, id: "site_name"
      %br
      = link_to 'Elegant software design for a more civilized age', root_url, id: "tagline"

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}

  %head
    %meta{charset: "utf-8"}
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}

    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %title Elegant Software Design for a More Civilized Age

  %body{:class => "#{controller_name} #{action_name}"}
    #wrapper
      = render 'layouts/header'

      #tab_pane
        #tabs
          %ul.tab_row
            = area :tabs do

              %li#default_tab.tab.selected
                Default tab

        #tabbed_content_pane
          = area :content do

            #default_content.tabbed_content
              Default content

      = render 'layouts/footer'

  :javascript
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'alightsabermind'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_entry_form">
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/posts/_index.html.haml
%br
- @posts.each do |post|
  = render "posts/post_display", post: post

app/views/posts/_post_display.html.haml
.blog_post.content

  - if post != nil

    .entry_title.title
      = link_to post.title, post
      - if !post.published?
        %span.unpublished_label
          \ - Unpublished

    .clearfix
      .post_comment_count
        - if ( !(controller_name == 'posts' && action_name == 'show') )
          = link_to "Comments", post_path(post, anchor: 'disqus_thread')
      .post_timestamp
        = post.created_at.strftime("%A, the #{post.created_at.day.ordinalize} of %B, %Y")

    .entry_content
      = markdown post.content
    %br

    - if ( controller_name == 'posts' && action_name == 'show' )
      #disqus_thread
      :javascript
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://YOUR-SITE.disqus.com/embed.js';
           (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();

      %noscript
        Please enable JavaScript to view the
        %a{:href=>"http://disqus.com/?ref_noscript=YOUR-SITE"}
          comments
        powered by Disqus.
      %a.dsq-brlink{:href=>"http://disqus.com"}
        comments powered by
        %span.logo-disqus Disqus

  - else
    No post with ID found

app/views/posts/_posts_admin_display_table.html.haml
%table.posts_display_table
  %tr#post_table_header_row.title
    %th Created At
    %th Title
    %th Content
    %th Show
    %th Edit
    %th Delete
    %th Published

  - @posts.each do |post|
    %tr{:id => ['post' + post.id.to_s], :class => 'post_row'}
      %td
        = post.created_at
      %td
        = truncate(post.title, length: 20, separator: ' ')
      %td
        = truncate(post.content, length: 40, separator: ' ')

      %td
        = link_to 'Show', post
      %td
        = link_to 'Edit', [:edit, post]
      %td
        = link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }

      - if post.published?
        %td
          = link_to 'Unpublish', toggle_published_post_path(post), {method: :put}
      - else
        %td
          = link_to 'Publish', toggle_published_post_path(post), {method: :put}

app/views/posts/admin.html.haml
= replace :tabs do
  %li#posts_admin_tab.tab
    Posts Admin

= replace :content do
  #posts_admin_content.tabbed_content
    = render 'posts/posts_admin_display_table', posts: @posts
    %br
    = button_to 'Create New Post', new_post_path, method: 'get', class: 'create_new_button'

app/views/posts/edit.html.haml
- replace :tabs do
  %li#posts_edit_tab.tab
    Edit Post

= replace :content do
  #posts_edit_content.tabbed_content
    %h1 Edit post

    .new_post
      = render 'form'

    = link_to 'Back', posts_path

app/views/posts/index.html.haml
- replace :tabs do
  = render 'shared/main_tabs'

- replace :content do
  = render 'shared/main_content'

app/views/posts/new.html.haml
- replace :tabs do
  %li#posts_new_tab.tab
    New Post

= replace :content do
  #posts_new_content.tabbed_content
    %h1 New post

    .new_post
      = render 'form'

    = link_to 'Back', posts_path

app/views/posts/show.html.haml
= replace :tabs do

  %li#welcome_tab.tab
    %span.tab_label
      Welcome
  %li#blog_tab.tab{data: {url: "#{request.env['ORIGINAL_FULLPATH']}"}}
    %span.tab_label
      Blog
  %li#projects_tab.tab
    %span.tab_label
      Projects
  %li#about_me_tab.tab
    %span.tab_label
      About

= replace :content do

  #welcome_content.tabbed_content
    = render "static/welcome_content"

  #blog_content.tabbed_content
    = link_to '<- Return to blog index', posts_path, :class => "content"
    %br
    %br
    = render "posts/post_display", post: @post

  #projects_content.tabbed_content
    = render 'projects/index'

  #about_me_content.tabbed_content
    = render "static/about_me_content"

app/views/projects/_form.html.erb
<%= form_for @project , html: {multipart: true} do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :screenshot %><br />
    <%= f.file_field :screenshot %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/projects/_index.html.haml
%br
- @projects.each do |project|
  = render "projects/project_display", project: project
  %br

app/views/projects/_project_display.html.haml
.project.content.clearfix

  - if project != nil

    .entry_title.title
      = link_to project.title, project
      - if !project.published?
        %span.unpublished_label
          \ - Unpublished

    - if ( !(controller_name == 'projects' && action_name == 'show') )
      = link_to "Comments", project_path(project, anchor: 'disqus_thread')
    %br

    = image_tag project.screenshot_url(:display).to_s

    .entry_content
      = markdown project.content


    - if ( controller_name == 'projects' && action_name == 'show' )
      %br
      #disqus_thread
      :javascript
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://YOUR-SITE.disqus.com/embed.js';
           (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();

      %noscript
        Please enable JavaScript to view the
        %a{:href=>"http://disqus.com/?ref_noscript=YOUR-SITE"}
          comments
        powered by Disqus.
      %a.dsq-brlink{:href=>"http://disqus.com"}
        comments powered by
        %span.logo-disqus Disqus

  - else
    No project with that ID found

app/views/projects/_projects_admin_display_table.html.haml
%table.projects_display_table
  %tr#project_table_header_row.title
    %th Created At
    %th Title
    %th Content
    %th Show
    %th Edit
    %th Delete
    %th Published

  - @projects.each do |project|
    %tr{:id => ['project' + project.id.to_s], :class => 'project_row'}
      %td
        = project.created_at
      %td
        = truncate(project.title, length: 20, separator: ' ')
      %td
        = truncate(project.content, length: 40, separator: ' ')

      %td
        = link_to 'Show', project
      %td
        = link_to 'Edit', [:edit, project]
      %td
        = link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }

      - if project.published?
        %td
          = link_to 'Unpublish', toggle_published_project_path(project), {method: :put}
      - else
        %td
          = link_to 'Publish', toggle_published_project_path(project), {method: :put}

app/views/projects/admin.html.haml
= replace :tabs do
  %li#projects_admin_tab.tab
    Projects Admin

= replace :content do
  #projects_admin_content.tabbed_content
    = render 'projects/projects_admin_display_table', projects: @projects
    %br
    = button_to 'Create New Project', new_project_path, method: 'get', class: 'create_new_button'

app/views/projects/edit.html.haml
- replace :tabs do
  %li#projects_edit_tab.tab
    Edit Project

= replace :content do
  #projects_edit_content.tabbed_content
    %h1 Edit project

    .new_project
      = render 'form'

    = link_to 'Back', projects_path

app/views/projects/index.html.haml
- replace :tabs do
  = render 'shared/main_tabs'

- replace :content do
  = render 'shared/main_content'

app/views/projects/new.html.haml
- replace :tabs do
  %li#projects_new_tab.tab
    New Project

= replace :content do
  #projects_new_content.tabbed_content
    %h1 New project

    .new_project
      = render 'form'

    = link_to 'Back', projects_path

app/views/projects/show.html.haml
= replace :tabs do

  %li#welcome_tab.tab
    %span.tab_label
      Welcome
  %li#blog_tab.tab
    %span.tab_label
      Blog
  %li#projects_tab.tab{data: {url: "#{request.env['ORIGINAL_FULLPATH']}"}}
    %span.tab_label
      Projects
  %li#about_me_tab.tab
    %span.tab_label
      About

= replace :content do

  #welcome_content.tabbed_content
    = render "static/welcome_content"

  #blog_content.tabbed_content
    = render "posts/index"

  #projects_content.tabbed_content
    = link_to '<- Return to Projects index', projects_path, :class => "content"
    %br
    %br
    = render "projects/project_display", project: @project

  #about_me_content.tabbed_content
    = render "static/about_me_content"

app/views/shared/_disqus_widget.html.erb
<div class='disqus_comment_holder'>
  <div id="disqus_w">
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'alightsabermind'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
  </div>
</div>

app/views/shared/_main_content.html.haml
#welcome_content.tabbed_content
  = render 'static/welcome_content'
#blog_content.tabbed_content
  = render 'posts/index'
#projects_content.tabbed_content
  = render 'projects/index'
#about_me_content.tabbed_content
  = render 'static/about_me_content'

app/views/shared/_main_tabs.html.haml
%li#welcome_tab.tab
  %span.tab_label
    Welcome
%li#blog_tab.tab
  %span.tab_label
    Blog
%li#projects_tab.tab
  %span.tab_label
    Projects
%li#about_me_tab.tab
  %span.tab_label
    About Me

app/views/shared/_post_display.html.erb
<% @commentable ? post = @commentable : nil %>
<div id="<%= dom_id(post) %>" class="blog_post">
  <div id="<%= dom_id(post) %>-title">

    <%= link_to post.title, post, :class => "entry_title title" %>

    <div>
      <%= link_to "Comments", post_path(post, anchor: 'disqus_thread'), :class => "post_comments_link" %>
    </div>

    <% if !post.published? %>
      <span class="unpublished_label"> - Unpublished</panel>
    <% end %>

  </div>

  <div id="<%= dom_id(post) %>-content" class="entry_content content">
    <p><%= markdown post.content %>
  </div>

  <div id="<%= dom_id(post) %>-author" class="entry_author">
    <b>Posted By:</b> <%= post.author.email %>
    <div class="entry_timestamp">
      <%= post.created_at.strftime("on %A, the #{post.created_at.day.ordinalize} of %B, %Y")  %>
    </div>
  </div>
</div>